package:
  name: "tricount"
  version: "1.3.0"

source:
  git_rev: v1.0.0
  git_url: https://github.com/Chuen-Lee/TriCount

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python

about:
  home: https://github.com/Chuen-Lee/TriCount
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "Counting beetles"

extra:
  recipe-maintainers:
    - Chuen-Lee
